### ISSUE TITLE
Some danish audio podcast don't play

### ISSUE THREAD

**Issue by kec2** [dersphere/plugin.video.itunes_podcasts#3]
Some danish audio podcast like "harddisken" and "detektor" does not play.

Below is the XBMC.log file:
###### 
# ... output of cat /storage/.xbmc/temp/xbmc.log
# OpenELEC release: Fusion.x86_64-2.95.6
# 
###### 

﻿13:04:04 T:140169067923264  NOTICE: -----------------------------------------------------------------------
13:04:05 T:140169067923264  NOTICE: Starting XBMC (12.0-RC2 Git:74b907c), Platform: Linux (OpenELEC - Version: 2.95.6, 3.6.11 x86_64). Built on Dec 20 2012
13:04:05 T:140169067923264  NOTICE: special://xbmc/ is mapped to: /usr/share/xbmc
13:04:05 T:140169067923264  NOTICE: special://xbmcbin/ is mapped to: /usr/lib/xbmc
13:04:05 T:140169067923264  NOTICE: special://masterprofile/ is mapped to: /storage/.xbmc/userdata
13:04:05 T:140169067923264  NOTICE: special://home/ is mapped to: /storage/.xbmc
13:04:05 T:140169067923264  NOTICE: special://temp/ is mapped to: /storage/.xbmc/temp
13:04:05 T:140169067923264  NOTICE: The executable running is: /usr/lib/xbmc/xbmc.bin
13:04:05 T:140169067923264  NOTICE: Local hostname: openelec
13:04:05 T:140169067923264  NOTICE: Log File is located: /storage/.xbmc/temp/xbmc.log
13:04:05 T:140169067923264  NOTICE: -----------------------------------------------------------------------
13:04:07 T:140169067923264   ERROR: CAESinkOSS::EnumerateDevicesEx - Failed to open mixer: /dev/mixer
13:04:07 T:140169067923264  NOTICE: Enumerated ALSA devices:
13:04:07 T:140169067923264  NOTICE:     Device 1
13:04:07 T:140169067923264  NOTICE:         m_deviceName      : hdmi:CARD=Generic,DEV=0
13:04:07 T:140169067923264  NOTICE:         m_displayName     : HD-Audio Generic
13:04:07 T:140169067923264  NOTICE:         m_displayNameExtra: HDMI
13:04:07 T:140169067923264  NOTICE:         m_deviceType      : AE_DEVTYPE_HDMI
13:04:07 T:140169067923264  NOTICE:         m_channels        : FL,FR
13:04:07 T:140169067923264  NOTICE:         m_sampleRates     : 32000,44100,48000
13:04:07 T:140169067923264  NOTICE:         m_dataFormats     : AE_FMT_S16NE,AE_FMT_S16LE
13:04:07 T:140169067923264  NOTICE:     Device 2
13:04:07 T:140169067923264  NOTICE:         m_deviceName      : @:CARD=Generic_1,DEV=0
13:04:07 T:140169067923264  NOTICE:         m_displayName     : HD-Audio Generic
13:04:07 T:140169067923264  NOTICE:         m_displayNameExtra: ALC892 Analog
13:04:07 T:140169067923264  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
13:04:07 T:140169067923264  NOTICE:         m_channels        : FL,FR
13:04:07 T:140169067923264  NOTICE:         m_sampleRates     : 44100,48000,96000,192000
13:04:07 T:140169067923264  NOTICE:         m_dataFormats     : AE_FMT_S32NE,AE_FMT_S16NE,AE_FMT_S16LE
13:04:07 T:140169067923264  NOTICE:     Device 3
13:04:07 T:140169067923264  NOTICE:         m_deviceName      : iec958:CARD=Generic_1,DEV=0
13:04:07 T:140169067923264  NOTICE:         m_displayName     : HD-Audio Generic
13:04:07 T:140169067923264  NOTICE:         m_displayNameExtra: ALC892 Digital S/PDIF
13:04:07 T:140169067923264  NOTICE:         m_deviceType      : AE_DEVTYPE_IEC958
13:04:07 T:140169067923264  NOTICE:         m_channels        : FL,FR
13:04:07 T:140169067923264  NOTICE:         m_sampleRates     : 32000,44100,48000,88200,96000,192000
13:04:07 T:140169067923264  NOTICE:         m_dataFormats     : AE_FMT_S32NE,AE_FMT_S16NE,AE_FMT_S16LE
13:04:07 T:140169067923264  NOTICE: load settings...
13:04:07 T:140169067923264  NOTICE: special://profile/ is mapped to: special://masterprofile/
13:04:07 T:140169067923264  NOTICE: loading special://masterprofile/guisettings.xml
13:04:07 T:140169067923264  NOTICE: Getting hardware information now...
13:04:07 T:140169067923264  NOTICE: Loading player core factory settings from special://xbmc/system/playercorefactory.xml.
13:04:07 T:140169067923264  NOTICE: Loaded playercorefactory configuration
13:04:07 T:140169067923264  NOTICE: Loading player core factory settings from special://masterprofile/playercorefactory.xml.
13:04:07 T:140169067923264  NOTICE: special://masterprofile/playercorefactory.xml does not exist. Skipping.
13:04:07 T:140169067923264  NOTICE: Loaded settings file from special://xbmc/system/advancedsettings.xml
13:04:07 T:140169067923264  NOTICE: Contents of special://xbmc/system/advancedsettings.xml are...
                                            <?xml version="1.0" encoding="UTF-8" ?>
                                            <advancedsettings>
                                              <splash>false</splash>
                                              <showexitbutton>false</showexitbutton>
                                              <cputempcommand>cputemp</cputempcommand>
                                              <gputempcommand>gputemp</gputempcommand>
                                              <video>
                                                <latency>
                                                  <delay>0</delay>
                                                  <refresh>
                                                    <min>23</min>
                                                    <max>24</max>
                                                    <delay>175</delay>
                                                  </refresh>
                                                </latency>
                                              </video>
                                              <samba>
                                                <clienttimeout>30</clienttimeout>
                                              </samba>
                                            </advancedsettings>
13:04:07 T:140169067923264  NOTICE: Getting hardware information now...
13:04:07 T:140169067923264  NOTICE: No settings file to load (special://masterprofile/advancedsettings.xml)
13:04:07 T:140169067923264  NOTICE: Default DVD Player: dvdplayer
13:04:07 T:140169067923264  NOTICE: Default Video Player: dvdplayer
13:04:07 T:140169067923264  NOTICE: Default Audio Player: paplayer
13:04:07 T:140169067923264  NOTICE: Disabled debug logging due to GUI setting. Level 0.
13:04:07 T:140169067923264  NOTICE: Log level changed to 0
13:04:07 T:140169067923264  NOTICE: Loading media sources from special://masterprofile/sources.xml
13:04:07 T:140169065752320  NOTICE: Thread CSoftAE start, auto delete: false
13:04:07 T:140169067923264  NOTICE: Running database version Addons15
13:04:07 T:140169052964608  NOTICE: Thread XBMC Peripherals start, auto delete: false
13:04:07 T:140169067923264  NOTICE: Setup SDL
13:04:07 T:140169067923264  NOTICE: Checking resolution 16
13:04:07 T:140169067923264 WARNING: CWinEventsX11::Init - no input method found
13:04:08 T:140169067923264  NOTICE: Using visual 0x29
13:04:08 T:140169067923264  NOTICE: GL_VENDOR = ATI Technologies Inc.
13:04:08 T:140169067923264  NOTICE: GL_RENDERER = AMD Radeon HD 7340 Graphics
13:04:08 T:140169067923264  NOTICE: GL_VERSION = 4.2.11931 Compatibility Profile Context
13:04:08 T:140169067923264  NOTICE: GL_SHADING_LANGUAGE_VERSION = 4.20
13:04:08 T:140169067923264  NOTICE: GL_EXTENSIONS = GL_AMDX_debug_output GL_AMDX_vertex_shader_tessellator GL_AMD_conservative_depth GL_AMD_debug_output GL_AMD_depth_clamp_separate GL_AMD_draw_buffers_blend GL_AMD_multi_draw_indirect GL_AMD_name_gen_delete GL_AMD_performance_monitor GL_AMD_pinned_memory GL_AMD_query_buffer_object GL_AMD_sample_positions GL_AMD_seamless_cubemap_per_texture GL_AMD_shader_stencil_export GL_AMD_shader_trace GL_AMD_texture_cube_map_array GL_AMD_texture_texture4 GL_AMD_transform_feedback3_lines_triangles GL_AMD_vertex_shader_layer GL_AMD_vertex_shader_tessellator GL_AMD_vertex_shader_viewport_index GL_ARB_ES2_compatibility GL_ARB_base_instance GL_ARB_blend_func_extended GL_ARB_color_buffer_float GL_ARB_compressed_texture_pixel_storage GL_ARB_conservative_depth GL_ARB_copy_buffer GL_ARB_depth_buffer_float GL_ARB_depth_clamp GL_ARB_depth_texture GL_ARB_draw_buffers GL_ARB_draw_buffers_blend GL_ARB_draw_elements_base_vertex GL_ARB_draw_indirect GL_ARB_draw_instanced GL_ARB_explicit_attrib_location GL_ARB_fragment_coord_conventions GL_ARB_fragment_program GL_ARB_fragment_program_shadow GL_ARB_fragment_shader GL_ARB_framebuffer_object GL_ARB_framebuffer_sRGB GL_ARB_geometry_shader4 GL_ARB_get_program_binary GL_ARB_gpu_shader5 GL_ARB_gpu_shader_fp64 GL_ARB_half_float_pixel GL_ARB_half_float_vertex GL_ARB_imaging GL_ARB_instanced_arrays GL_ARB_internalformat_query GL_ARB_map_buffer_alignment GL_ARB_map_buffer_range GL_ARB_multisample GL_ARB_multitexture GL_ARB_occlusion_query GL_ARB_occlusion_query2 GL_ARB_pixel_buffer_object GL_ARB_point_parameters GL_ARB_point_sprite GL_ARB_provoking_vertex GL_ARB_sample_shading GL_ARB_sampler_objects GL_ARB_seamless_cube_map GL_ARB_separate_shader_objects GL_ARB_shader_atomic_counters GL_ARB_shader_bit_encoding GL_ARB_shader_image_load_store GL_ARB_shader_objects GL_ARB_shader_precision GL_ARB_shader_stencil_export GL_ARB_shader_subroutine GL_ARB_shader_texture_lod GL_ARB_shading_language_100 GL_ARB_shading_language_420pack GL_ARB_shading_language_packing GL_ARB_shadow GL_ARB_shadow_ambient GL_ARB_sync GL_ARB_tessellation_shader GL_ARB_texture_border_clamp GL_ARB_texture_buffer_object GL_ARB_texture_buffer_object_rgb32 GL_ARB_texture_compression GL_ARB_texture_compression_bptc GL_ARB_texture_compression_rgtc GL_ARB_texture_cube_map GL_ARB_texture_cube_map_array GL_ARB_texture_env_add GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar GL_ARB_texture_env_dot3 GL_ARB_texture_float GL_ARB_texture_gather GL_ARB_texture_mirrored_repeat GL_ARB_texture_multisample GL_ARB_texture_non_power_of_two GL_ARB_texture_query_lod GL_ARB_texture_rectangle GL_ARB_texture_rg GL_ARB_texture_rgb10_a2ui GL_ARB_texture_snorm GL_ARB_texture_storage GL_ARB_timer_query GL_ARB_transform_feedback2 GL_ARB_transform_feedback3 GL_ARB_transform_feedback_instanced GL_ARB_transpose_matrix GL_ARB_uniform_buffer_object GL_ARB_vertex_array_bgra GL_ARB_vertex_array_object GL_ARB_vertex_attrib_64bit GL_ARB_vertex_buffer_object GL_ARB_vertex_program GL_ARB_vertex_shader GL_ARB_vertex_type_2_10_10_10_rev GL_ARB_viewport_array GL_ARB_window_pos GL_ATI_draw_buffers GL_ATI_envmap_bumpmap GL_ATI_fragment_shader GL_ATI_meminfo GL_ATI_separate_stencil GL_ATI_texture_compression_3dc GL_ATI_texture_env_combine3 GL_ATI_texture_float GL_ATI_texture_mirror_once GL_EXT_abgr GL_EXT_bgra GL_EXT_bindable_uniform GL_EXT_blend_color GL_EXT_blend_equation_separate GL_EXT_blend_func_separate GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_compiled_vertex_array GL_EXT_copy_buffer GL_EXT_copy_texture GL_EXT_direct_state_access GL_EXT_draw_buffers2 GL_EXT_draw_instanced GL_EXT_draw_range_elements GL_EXT_fog_coord GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_EXT_framebuffer_object GL_EXT_framebuffer_sRGB GL_EXT_geometry_shader4 GL_EXT_gpu_program_parameters GL_EXT_gpu_shader4 GL_EXT_histogram GL_EXT_multi_draw_arrays GL_EXT_packed_depth_stencil GL_EXT_packed_float GL_EXT_packed_pixels GL_EXT_pixel_buffer_object GL_EXT_point_parameters GL_EXT_provoking_vertex GL_EXT_rescale_normal GL_EXT_secondary_color GL_EXT_separate_specular_color GL_EXT_shader_image_load_store GL_EXT_shadow_funcs GL_EXT_stencil_wrap GL_EXT_subtexture GL_EXT_texgen_reflection GL_EXT_texture3D GL_EXT_texture_array GL_EXT_texture_buffer_object GL_EXT_texture_compression_bptc GL_EXT_texture_compression_latc GL_EXT_texture_compression_rgtc GL_EXT_texture_compression_s3tc GL_EXT_texture_cube_map GL_EXT_texture_edge_clamp GL_EXT_texture_env_add GL_EXT_texture_env_combine GL_EXT_texture_env_dot3 GL_EXT_texture_filter_anisotropic GL_EXT_texture_integer GL_EXT_texture_lod GL_EXT_texture_lod_bias GL_EXT_texture_mirror_clamp GL_EXT_texture_object GL_EXT_texture_rectangle GL_EXT_texture_sRGB GL_EXT_texture_sRGB_decode GL_EXT_texture_shared_exponent GL_EXT_texture_snorm GL_EXT_texture_storage GL_EXT_texture_swizzle GL_EXT_timer_query GL_EXT_transform_feedback GL_EXT_vertex_array GL_EXT_vertex_array_bgra GL_EXT_vertex_attrib_64bit GL_IBM_texture_mirrored_repeat GL_KTX_buffer_region GL_NV_blend_square GL_NV_conditional_render GL_NV_copy_depth_to_color GL_NV_copy_image GL_NV_explicit_multisample GL_NV_float_buffer GL_NV_half_float GL_NV_primitive_restart GL_NV_texgen_reflection GL_NV_texture_barrier GL_SGIS_generate_mipmap GL_SGIS_texture_edge_clamp GL_SGIS_texture_lod GL_SUN_multi_draw_arrays GL_WIN_swap_hint
13:04:08 T:140169067923264  NOTICE: Running database version Addons15
13:04:08 T:140169067923264  NOTICE: Running database version ViewModes4
13:04:08 T:140169067923264  NOTICE: Running database version Textures13
13:04:08 T:140169067923264  NOTICE: Running database version MyMusic32
13:04:08 T:140169067923264  NOTICE: Running database version MyVideos75
13:04:08 T:140169067923264  NOTICE: Running database version TV22
13:04:08 T:140169067923264  NOTICE: Running database version Epg7
13:04:08 T:140169067923264  NOTICE: start dvd mediatype detection
13:04:08 T:140169067923264  NOTICE: initializing playlistplayer
13:04:08 T:140169067923264  NOTICE: DONE initializing playlistplayer
13:04:08 T:140169009297152  NOTICE: Thread CDetectDVDMedia start, auto delete: false
13:04:09 T:140168914704128  NOTICE: Thread XBPyThread start, auto delete: false
13:04:09 T:140169067923264  NOTICE: Previous line repeats 2 times.
13:04:09 T:140169067923264  NOTICE: initialize done
13:04:09 T:140168889526016  NOTICE: Thread XBPyThread start, auto delete: false
13:04:09 T:140169067923264  NOTICE: Enabled Joystick: Logitech Logitech Cordless RumblePad 2
13:04:09 T:140169067923264  NOTICE: Details: Total Axis: 4 Total Hats: 1 Total Buttons: 12
13:04:09 T:140169067923264  NOTICE: Running the application...
13:04:09 T:140168897918720  NOTICE: -->Python Interpreter Initialized<--
13:04:09 T:140168914704128  NOTICE: -->Python Interpreter Initialized<--
13:04:09 T:140168906311424  NOTICE: -->Python Interpreter Initialized<--
13:04:09 T:140168889526016  NOTICE: -->Python Interpreter Initialized<--
13:04:09 T:140168578246400  NOTICE: Thread Jobworker start, auto delete: true
13:04:09 T:140169067923264  NOTICE: ES: Starting event server
13:04:09 T:140168561403648  NOTICE: Thread CEventServer start, auto delete: false
13:04:09 T:140168561403648  NOTICE: ES: Starting UDP Event server on 0.0.0.0:9777
13:04:09 T:140168561403648  NOTICE: UDP: Listening on port 9777
13:04:09 T:140168553010944  NOTICE: Thread CTCPServer start, auto delete: false
13:04:09 T:140169067923264  NOTICE: starting zeroconf publishing
13:04:09 T:140168396793600  NOTICE: Thread Jobworker start, auto delete: true
13:04:09 T:140169009297152  NOTICE: Thread CRssReader start, auto delete: false
13:04:09 T:140168889526016  NOTICE:  StorageServer Module loaded RUN
13:04:09 T:140168889526016  NOTICE: StorageClient-1.3.0 Starting server
13:04:09 T:140168889526016  NOTICE: StorageServer-1.3.0 Storage Server starting /storage/.xbmc/userdata/Database/commoncache.db
13:04:09 T:140168906311424  NOTICE: Artwork Downloader: ## Service - Run at startup: False
13:04:09 T:140168906311424  NOTICE: Artwork Downloader: ## Service - Delayed startup:  minutes
13:04:09 T:140168906311424  NOTICE: Artwork Downloader: ## Service - Run as service: False
13:04:09 T:140168906311424  NOTICE: Artwork Downloader: ## Service - Time: :00
14:04:12 T:140169009297152  NOTICE: Thread CRssReader start, auto delete: false
14:04:21 T:140168906311424  NOTICE: Thread Jobworker start, auto delete: true
14:04:29 T:140169067923264  NOTICE: Previous line repeats 1 times.
14:04:29 T:140169067923264 WARNING: GetLabel - Unknown nodetype requested 0
14:04:29 T:140168388400896 WARNING: Previous line repeats 1 times.
14:04:29 T:140168388400896  NOTICE: Thread Background Loader start, auto delete: false
14:04:31 T:140168388400896  NOTICE: Thread XBPyThread start, auto delete: false
14:04:31 T:140168388400896  NOTICE: -->Python Interpreter Initialized<--
14:04:32 T:140168388400896  NOTICE: [xbmcswift2] Request for "/" matches rule for function "show_root"
14:04:32 T:140168352040704  NOTICE: Thread Background Loader start, auto delete: false
14:04:35 T:140168388400896  NOTICE: Thread XBPyThread start, auto delete: false
14:04:35 T:140168388400896  NOTICE: -->Python Interpreter Initialized<--
14:04:35 T:140168388400896  NOTICE: [xbmcswift2] Request for "/audio/podcasts/search/" matches rule for function "search"
14:04:35 T:140168388400896 WARNING: [plugin.video.itunes_podcasts] String is missing: search
14:05:20 T:140168388400896  NOTICE: [xbmcswift2] Request for "/audio/podcasts/search/harddisk/" matches rule for function "search_result"
14:05:20 T:140168388400896   ERROR: NEWADDON Invalid Date Format ""
14:05:20 T:140168906311424   ERROR: Previous line repeats 12 times.
14:05:20 T:140168906311424  NOTICE: Thread Background Loader start, auto delete: false
14:05:20 T:140168578246400  NOTICE: Thread Jobworker start, auto delete: true
14:05:26 T:140168914704128  NOTICE: Thread XBPyThread start, auto delete: false
14:05:26 T:140168914704128  NOTICE: -->Python Interpreter Initialized<--
14:05:26 T:140168914704128  NOTICE: [xbmcswift2] Request for "/audio/podcast/items/299496725/" matches rule for function "show_items"
14:05:28 T:140168914704128   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: invalid literal for int() with base 10: ''
                                            Traceback (most recent call last):
                                              File "/storage/.xbmc/addons/plugin.video.itunes_podcasts/addon.py", line 291, in <module>
                                                plugin.run()
                                              File "/storage/.xbmc/addons/script.module.xbmcswift2/lib/xbmcswift2/plugin.py", line 319, in run
                                                items = self._dispatch(self.request.path)
                                              File "/storage/.xbmc/addons/script.module.xbmcswift2/lib/xbmcswift2/plugin.py", line 295, in _dispatch
                                                listitems = view_func(**items)
                                              File "/storage/.xbmc/addons/plugin.video.itunes_podcasts/addon.py", line 105, in show_items
                                                podcast_id=podcast_id
                                              File "/storage/.xbmc/addons/plugin.video.itunes_podcasts/resources/lib/api.py", line 200, in get_podcast_items
                                                'size': int(link.get('length', 0)),
                                            ValueError: invalid literal for int() with base 10: ''
                                            -->End of Python script error report<--
14:05:28 T:140169067923264   ERROR: GetDirectory - Error getting plugin://plugin.video.itunes_podcasts/audio/podcast/items/299496725/
14:05:28 T:140169067923264   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.itunes_podcasts/audio/podcast/items/299496725/) failed
14:05:28 T:140168914704128  NOTICE: Thread Background Loader start, auto delete: false
14:05:31 T:140168914704128  NOTICE: Thread XBPyThread start, auto delete: false
14:05:32 T:140168914704128  NOTICE: -->Python Interpreter Initialized<--
14:05:32 T:140168914704128  NOTICE: [xbmcswift2] Request for "/audio/podcast/items/374892177/" matches rule for function "show_items"
14:05:34 T:140168914704128   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: invalid literal for int() with base 10: ''
                                            Traceback (most recent call last):
                                              File "/storage/.xbmc/addons/plugin.video.itunes_podcasts/addon.py", line 291, in <module>
                                                plugin.run()
                                              File "/storage/.xbmc/addons/script.module.xbmcswift2/lib/xbmcswift2/plugin.py", line 319, in run
                                                items = self._dispatch(self.request.path)
                                              File "/storage/.xbmc/addons/script.module.xbmcswift2/lib/xbmcswift2/plugin.py", line 295, in _dispatch
                                                listitems = view_func(**items)
                                              File "/storage/.xbmc/addons/plugin.video.itunes_podcasts/addon.py", line 105, in show_items
                                                podcast_id=podcast_id
                                              File "/storage/.xbmc/addons/plugin.video.itunes_podcasts/resources/lib/api.py", line 200, in get_podcast_items
                                                'size': int(link.get('length', 0)),
                                            ValueError: invalid literal for int() with base 10: ''
                                            -->End of Python script error report<--
14:05:34 T:140169067923264   ERROR: GetDirectory - Error getting plugin://plugin.video.itunes_podcasts/audio/podcast/items/374892177/
14:05:34 T:140169067923264   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.itunes_podcasts/audio/podcast/items/374892177/) failed
14:05:34 T:140168914704128  NOTICE: Thread Background Loader start, auto delete: false
14:05:59 T:140169067923264  NOTICE: Samba is idle. Closing the remaining connections

**Comment by dersphere** [comment]
Thanks for reporting!
